"""Exact maximum-weight parallel commitment research package."""

from mwpc_exact.adaptive import (
    AdaptiveSupportConfig,
    SupportGrowthPolicy,
    solve_exact_commit_adaptive,
    solve_exact_commit_adaptive_validated,
)
from mwpc_exact.backend import ExactBackend
from mwpc_exact.byte_lattice import ByteLattice, ByteLatticePath, build_byte_lattice
from mwpc_exact.decoder import (
    CommitGuarantee,
    CommitSource,
    DecoderStepResult,
    FailureFallbackCallable,
    FailureFallbackHandler,
    FailureFallbackRequest,
    FailureFallbackStrategy,
    FallbackSelection,
    FallbackToken,
    TokenCommit,
    apply_exact_commit_result,
)
from mwpc_exact.eos_lattice import (
    EOSArc,
    EOSLattice,
    EOSLatticePath,
    build_eos_lattice,
)
from mwpc_exact.eos_policy import (
    EOSMode,
    EOSPolicy,
    EOSPolicyViolation,
    EOSState,
    TokenRole,
)
from mwpc_exact.epic_selection import (
    EPIC_UPSTREAM_COMMIT,
    EpicSelectionContext,
    select_epic,
)
from mwpc_exact.finite_solver import solve_ordinary_support_reference
from mwpc_exact.profiling import ComponentProfiler, ProfilingComponent, ProfilingEvent
from mwpc_exact.proposal_policy import (
    ProposalWeightMode,
    ScheduleProposalBatch,
    build_schedule_proposals,
)
from mwpc_exact.selection import (
    SelectionInput,
    SelectionResult,
    SelectionStatus,
    SelectorKind,
    recompute_witness_selection,
    select_exact,
    select_serial,
)
from mwpc_exact.solver import solve_exact_commit, solve_validated_exact_commit
from mwpc_exact.strategy import (
    CommitStrategy,
    DecoderStrategyConfig,
    ExactStrategyConfig,
    add_commit_strategy_arguments,
    build_commit_strategy_parser,
    decoder_strategy_config_from_namespace,
    dispatch_commit_strategy,
    legacy_commit_strategy,
)
from mwpc_exact.support import (
    PerPositionSupport,
    SupportInputSource,
    SupportPolicy,
    build_per_position_support,
    canonical_support_rows_json,
    support_rows_sha256,
)
from mwpc_exact.token_lattice import (
    TokenChoice,
    TokenLattice,
    TokenLatticePath,
    build_token_lattice,
)
from mwpc_exact.tokenizer_bytes import (
    BYTE_LEVEL_ALPHABET,
    CompositionalByteLevelAdapter,
    UnsupportedTokenError,
    byte_level_piece_to_bytes,
)
from mwpc_exact.types import (
    AggregatedProposal,
    EpsilonEdge,
    ExactCommitResult,
    ExactnessScope,
    Proposal,
    SolveStatus,
    SupportKind,
    TerminalEdge,
    TokenArc,
    WeightedTerminalDAG,
    aggregate_proposals,
)
from mwpc_exact.validated import ValidatedExactCommit
from mwpc_exact.validator import (
    EOSWitnessValidator,
    GrammarRecognizer,
    SupportWitnessValidator,
    TokenizerWitnessValidator,
    ValidationCode,
    ValidationIssue,
    ValidationReport,
    validate_exact_commit_certificate,
)

__all__ = [
    "BYTE_LEVEL_ALPHABET",
    "EPIC_UPSTREAM_COMMIT",
    "AdaptiveSupportConfig",
    "AggregatedProposal",
    "ByteLattice",
    "ByteLatticePath",
    "CommitGuarantee",
    "CommitSource",
    "CommitStrategy",
    "ComponentProfiler",
    "CompositionalByteLevelAdapter",
    "DecoderStepResult",
    "DecoderStrategyConfig",
    "EOSArc",
    "EOSLattice",
    "EOSLatticePath",
    "EOSMode",
    "EOSPolicy",
    "EOSPolicyViolation",
    "EOSState",
    "EOSWitnessValidator",
    "EpicSelectionContext",
    "EpsilonEdge",
    "ExactBackend",
    "ExactCommitResult",
    "ExactStrategyConfig",
    "ExactnessScope",
    "FailureFallbackCallable",
    "FailureFallbackHandler",
    "FailureFallbackRequest",
    "FailureFallbackStrategy",
    "FallbackSelection",
    "FallbackToken",
    "GrammarRecognizer",
    "PerPositionSupport",
    "ProfilingComponent",
    "ProfilingEvent",
    "Proposal",
    "ProposalWeightMode",
    "ScheduleProposalBatch",
    "SelectionInput",
    "SelectionResult",
    "SelectionStatus",
    "SelectorKind",
    "SolveStatus",
    "SupportGrowthPolicy",
    "SupportInputSource",
    "SupportKind",
    "SupportPolicy",
    "SupportWitnessValidator",
    "TerminalEdge",
    "TokenArc",
    "TokenChoice",
    "TokenCommit",
    "TokenLattice",
    "TokenLatticePath",
    "TokenRole",
    "TokenizerWitnessValidator",
    "UnsupportedTokenError",
    "ValidatedExactCommit",
    "ValidationCode",
    "ValidationIssue",
    "ValidationReport",
    "WeightedTerminalDAG",
    "add_commit_strategy_arguments",
    "aggregate_proposals",
    "apply_exact_commit_result",
    "build_byte_lattice",
    "build_commit_strategy_parser",
    "build_eos_lattice",
    "build_per_position_support",
    "build_schedule_proposals",
    "build_token_lattice",
    "byte_level_piece_to_bytes",
    "canonical_support_rows_json",
    "decoder_strategy_config_from_namespace",
    "dispatch_commit_strategy",
    "legacy_commit_strategy",
    "recompute_witness_selection",
    "select_epic",
    "select_exact",
    "select_serial",
    "solve_exact_commit",
    "solve_exact_commit_adaptive",
    "solve_exact_commit_adaptive_validated",
    "solve_ordinary_support_reference",
    "solve_validated_exact_commit",
    "support_rows_sha256",
    "validate_exact_commit_certificate",
]
