"""Exact maximum-weight parallel commitment research package."""

from mwpc_exact.byte_lattice import ByteLattice, ByteLatticePath, build_byte_lattice
from mwpc_exact.eos_lattice import (
    EOSArc,
    EOSLattice,
    EOSLatticePath,
    EOSMode,
    EOSPolicy,
    EOSPolicyViolation,
    EOSState,
    TokenRole,
    build_eos_lattice,
)
from mwpc_exact.finite_solver import ExactBackend, solve_exact_commit
from mwpc_exact.proposal_policy import (
    ProposalWeightMode,
    ScheduleProposalBatch,
    build_schedule_proposals,
)
from mwpc_exact.support import (
    PerPositionSupport,
    SupportInputSource,
    SupportPolicy,
    build_per_position_support,
    canonical_support_rows_json,
    support_rows_sha256,
)
from mwpc_exact.token_lattice import (
    TokenChoice,
    TokenLattice,
    TokenLatticePath,
    build_token_lattice,
)
from mwpc_exact.tokenizer_bytes import (
    BYTE_LEVEL_ALPHABET,
    CompositionalByteLevelAdapter,
    UnsupportedTokenError,
    byte_level_piece_to_bytes,
)
from mwpc_exact.types import (
    AggregatedProposal,
    EpsilonEdge,
    ExactCommitResult,
    ExactnessScope,
    Proposal,
    SolveStatus,
    SupportKind,
    TerminalEdge,
    TokenArc,
    WeightedTerminalDAG,
    aggregate_proposals,
)
from mwpc_exact.validator import (
    EOSWitnessValidator,
    GrammarRecognizer,
    SupportWitnessValidator,
    TokenizerWitnessValidator,
    ValidationCode,
    ValidationIssue,
    ValidationReport,
    validate_exact_commit_certificate,
)

__all__ = [
    "BYTE_LEVEL_ALPHABET",
    "AggregatedProposal",
    "ByteLattice",
    "ByteLatticePath",
    "CompositionalByteLevelAdapter",
    "EOSArc",
    "EOSLattice",
    "EOSLatticePath",
    "EOSMode",
    "EOSPolicy",
    "EOSPolicyViolation",
    "EOSState",
    "EOSWitnessValidator",
    "EpsilonEdge",
    "ExactBackend",
    "ExactCommitResult",
    "ExactnessScope",
    "GrammarRecognizer",
    "PerPositionSupport",
    "Proposal",
    "ProposalWeightMode",
    "ScheduleProposalBatch",
    "SolveStatus",
    "SupportInputSource",
    "SupportKind",
    "SupportPolicy",
    "SupportWitnessValidator",
    "TerminalEdge",
    "TokenArc",
    "TokenChoice",
    "TokenLattice",
    "TokenLatticePath",
    "TokenRole",
    "TokenizerWitnessValidator",
    "UnsupportedTokenError",
    "ValidationCode",
    "ValidationIssue",
    "ValidationReport",
    "WeightedTerminalDAG",
    "aggregate_proposals",
    "build_byte_lattice",
    "build_eos_lattice",
    "build_per_position_support",
    "build_schedule_proposals",
    "build_token_lattice",
    "byte_level_piece_to_bytes",
    "canonical_support_rows_json",
    "solve_exact_commit",
    "support_rows_sha256",
    "validate_exact_commit_certificate",
]
