import MWPC

#print axioms MWPC.certified_optimal
#print axioms MWPC.certified_infeasible
#print axioms MWPC.batch_upper
#print axioms MWPC.upper_attained
#print axioms MWPC.certified_gap
#print axioms MWPC.multiplicative_bound
#print axioms MWPC.bound_attainment
#print axioms MWPC.closing_emits_token
#print axioms MWPC.unique_prefixes_membership
#print axioms MWPC.compact_node_count
#print axioms MWPC.representation_preserves_optima
#print axioms MWPC.same_input_dominance
#print axioms MWPC.fixed_reward_preserves_optimum
#print axioms MWPC.support_expansion_certificate
#print axioms MWPC.optimum_monotone
#print axioms MWPC.minimum_capacity
#print axioms MWPC.witness_update_preserves_feasibility
#print axioms MWPC.conflict_missing_member
#print axioms MWPC.empty_conflict_infeasible
#print axioms MWPC.conflict_cover_bound
#print axioms MWPC.conflict_certified_optimal
#print axioms MWPC.conflict_transport
#print axioms MWPC.fixed_conflict_discharge
#print axioms MWPC.amortized_conflict_queries
#print axioms MWPC.feasible_witness_transport
#print axioms MWPC.partition_mass_envelope
#print axioms MWPC.conditional_missing_bound
#print axioms MWPC.conditional_l1_numerator
#print axioms MWPC.conditional_event_lower
#print axioms MWPC.conditional_event_upper
#print axioms MWPC.finite_error_budget
#print axioms MWPC.closed_yield_envelope
#print axioms MWPC.support_coverage_transport
#print axioms MWPC.grammar_yield_alphabet
#print axioms MWPC.alphabet_support_transport
