import MWPC.AdaptiveSemantics

#print axioms MWPC.row_product_scaling
#print axioms MWPC.opening_stacks_count
#print axioms MWPC.opening_stacks_distinct
#print axioms MWPC.fooling_routes_injective
#print axioms MWPC.fooling_state_count
#print axioms MWPC.exponential_fooling_state_bound
#print axioms MWPC.semantic_bit_fooling
#print axioms MWPC.semantic_word_fooling
#print axioms MWPC.semantic_witnesses_count
#print axioms MWPC.semantic_witnesses_distinct
#print axioms MWPC.semantic_rectangle_cover_bound
#print axioms MWPC.semantic_witness_length
#print axioms MWPC.semantic_coordinate_union
#print axioms MWPC.semantic_witness_union
#print axioms MWPC.semantic_nonnegative_bilinear_lower_bound
#print axioms MWPC.semantic_refinement_new
#print axioms MWPC.semantic_refinement_progress
#print axioms MWPC.semantic_refinement_bound
#print axioms MWPC.semantic_zero_violations_imply
#print axioms MWPC.semantic_core_complete
#print axioms MWPC.semantic_core_arbitrary_reweighting
#print axioms MWPC.parity_append
#print axioms MWPC.parity_zeros
#print axioms MWPC.parity_prefix_extend
#print axioms MWPC.binary_words_count
#print axioms MWPC.binary_words_length
#print axioms MWPC.binary_words_distinct
#print axioms MWPC.parity_bad_value
#print axioms MWPC.parity_bad_injective
#print axioms MWPC.parity_exclusion_prefix_unique
#print axioms MWPC.parity_prefix_exclusion_bound
